### ISSUE TITLE
Unable To Vote

### ISSUE THREAD

**Issue by MyDude52** [pomodori92/voteBot#7]
I have edited the appropriate values, and have puppeteer installed into the directory but cannot seem to get this to work. It throws this error. 

"Page opened. C:\Users\User\Desktop\voteBot-main\voteBot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\CallbackRegistry.js:96 #error = new Errors_js_1.ProtocolError(); ^ ProtocolError: Protocol error (Page.navigate): Invalid parameters Failed to deserialize params.url - BINDINGS: mandatory field missing at position 50 at <instance_members_initializer> (C:\Users\User\Desktop\voteBot-main\voteBot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\CallbackRegistry.js:96:14) at new Callback (C:\Users\User\Desktop\voteBot-main\voteBot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\CallbackRegistry.js:100:16) at CallbackRegistry.create (C:\Users\User\Desktop\voteBot-main\voteBot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\CallbackRegistry.js:22:26) at Connection._rawSend (C:\Users\User\Desktop\voteBot-main\voteBot\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Connection.js:80:26) at CdpCDPSession.send (C:\Users\User\Desktop\voteBot-main\voteBot\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\CDPSession.js:66:33) at navigate (C:\Users\User\Desktop\voteBot-main\voteBot\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Frame.js:160:51) at CdpFrame.goto (C:\Users\User\Desktop\voteBot-main\voteBot\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Frame.js:138:17) at CdpFrame. (C:\Users\User\Desktop\voteBot-main\voteBot\node_modules\puppeteer-core\lib\cjs\puppeteer\util\decorators.js:98:27) at CdpPage.goto (C:\Users\User\Desktop\voteBot-main\voteBot\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:590:43) at C:\Users\User\Desktop\voteBot-main\voteBot\voteBot.js:26:13 Node.js v20.11.1 %y Waiting for 0 seconds, press a key to continue ..."

Here is the code to my edited votebot.js file.

const puppeteer = require('puppeteer');

(async () => {
// 	const pollURL = 'https://poll.fm/13620958';
// 	const answerId = 'PDI_answer60846693';
	const pollURL = process.env.POLLURL;
	const answerId = process.env.ANSWERID;

	const browser = await puppeteer.launch({
		args: [
			'--no-sandbox',
			'--disable-setuid-sandbox'
		]
	});
	const page = await browser.newPage();
	await page.setViewport({
		width: 1920,
		height: 1080,
		deviceScaleFactor: 3,
		isMobile: false,
		hasTouch: false,
		isLandscape: false
	});
	console.log('Page opened.');

	await page.goto(pollURL, { waitUntil: 'networkidle2' });
	console.log('Page loaded.');

	await page.waitForSelector('#' + answerId);
	await page.click('input#' + answerId);
	console.log('Answer chosen.');

	await page.waitForSelector('#poll > div > div > div > div > main > form > div.css-vote.pds-vote > div > a');
	await page.click('#poll > div > div > div > div > main > form > div.css-vote.pds-vote > div > a');
	console.log('Voted.');
	setTimeout(function() {
		browser.close();
	}, 500);
	console.log('Finished Iteration');
	 

})();

**Comment by pomodori92** [comment]
Thanks for reporting this error to me.

Unfortunately I haven't updated this program for a long time. I'll do some tests in the next few days and let you know. In the meantime, if you have other details, write me another comment.

**Comment by pomodori92** [comment]
This bot used to be specific to the poll.fm website, but I just verified that it no longer exists and you are redirected to crowdsignal.com.

Could you write me the URL of the survey? Maybe I'll try modifying it for your purposes.

**Comment by MyDude52** [comment]
> Thanks for reporting this error to me.
> 
> Unfortunately I haven't updated this program for a long time. I'll do some tests in the next few days and let you know. In the meantime, if you have other details, write me another comment.

Its all good man. I got it working with some personal tweaks and using ChatGPT to troubleshoot the error. This is the code that works. 

const puppeteer = require('puppeteer');



(async () => {

    try {

        const pollURL = process.env.POLLURL || 'https://poll.fm/13620958';

        const answerId = process.env.ANSWERID || 'PDI_answer60846693';



        const browser = await puppeteer.launch({

            args: [

                '--no-sandbox',

                '--disable-setuid-sandbox'

            ]

        });

        const page = await browser.newPage();

        await page.setViewport({

            width: 1920,

            height: 1080,

            deviceScaleFactor: 1,

        });

        console.log('Page opened.');



        await page.goto(pollURL, { waitUntil: 'networkidle2' });

        console.log('Page loaded.');



        await page.waitForSelector('#' + answerId);

        await page.click('input#' + answerId);

        console.log('Answer chosen.');



        await page.waitForSelector('#poll > div > div > div > div > main > form > div.css-vote.pds-vote > div > a');

        await page.click('#poll > div > div > div > div > main > form > div.css-vote.pds-vote > div > a');

        console.log('Voted.');



        await delay(500); // Wait for 500 milliseconds

        await browser.close();

        console.log('Browser closed.');

    } catch (error) {

        console.error('Error:', error);

    }

})();



async function delay(ms) {

    return new Promise(resolve => setTimeout(resolve, ms));

}

**Comment by pomodori92** [comment]
Thank you!  Could you make a Pull Request with this solution?

However, the bot was created specifically for the poll.fm website, which no longer exists.
Which survey website did you want to use it for? Maybe I could edit it specifically for that site.

**Comment by eharvilicz** [comment]
Can someone here help me get this working for this poll? 

 https://www.pennlive.com/highschoolsports/2026/05/vote-who-is-the-best-goalie-in-pa-high-school-lacrosse-in-2026.html
Spencer Musti, sr., Bishop McDevitt

I get it to run, but it looks like it puts an extra '#' in the answer ID.  `#PDI_answer74582825`

**Comment by eharvilicz** [comment]
I'm getting the folowing error:

Error: TimeoutError: Waiting for selector `#PDI_answer74582825` failed
    at CSSQueryHandler.waitFor (file:///Users/ericharvilicz/voteBot/node_modules/puppeteer-core/lib/puppeteer/common/QueryHandler.js:211:46)
    at async CdpFrame.waitForSelector (file:///Users/ericharvilicz/voteBot/node_modules/puppeteer-core/lib/puppeteer/api/Frame.js:541:21)
    at async CdpPage.waitForSelector (file:///Users/ericharvilicz/voteBot/node_modules/puppeteer-core/lib/puppeteer/api/Page.js:1387:20)
    at async /Users/ericharvilicz/voteBot/voteBot.js:47:5 {
  cause: TimeoutError: Waiting failed: 30000ms exceeded
      at new WaitTask (file:///Users/ericharvilicz/voteBot/node_modules/puppeteer-core/lib/puppeteer/common/WaitTask.js:46:34)
      at IsolatedWorld.waitForFunction (file:///Users/ericharvilicz/voteBot/node_modules/puppeteer-core/lib/puppeteer/api/Realm.js:49:26)
      at CSSQueryHandler.waitFor (file:///Users/ericharvilicz/voteBot/node_modules/puppeteer-core/lib/puppeteer/common/QueryHandler.js:176:95)
      at async CdpFrame.waitForSelector (file:///Users/ericharvilicz/voteBot/node_modules/puppeteer-core/lib/puppeteer/api/Frame.js:541:21)
      at async CdpPage.waitForSelector (file:///Users/ericharvilicz/voteBot/node_modules/puppeteer-core/lib/puppeteer/api/Page.js:1387:20)
      at async /Users/ericharvilicz/voteBot/voteBot.js:47:5

**Comment by pomodori92** [comment]
Hello @eharvilicz,

this bot was made for Poll.fm, not for other websites.
